spring:
  profiles:
    include: common
  application:
    name: alert-config-service
  # Database configuration (points to the same DB as the processor)
  datasource:
    url: jdbc:postgresql://localhost:5432/alert_db
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD}
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      # Use 'none' as Flyway in the other service manages the schema
      ddl-auto: none
    show-sql: false

application:
  security:
    jwt:
      # IMPORTANT: Generate a strong, random, Base64 secret key for production.
      secret-key: ${JWT_SECRET_KEY}
      # Access token expiration in milliseconds (15 minutes for better security)
      expiration: 900000
      refresh-token:
        # Refresh token expiration in milliseconds (7 days)
        expiration: 604800000

server:
  port: 8081 # Run on a different port than other services