spring:
  profiles:
    include: common
  application:
    name: data-ingestor-service

# Alpaca WebSocket API configuration
alpaca:
  # Use paper-trading sandbox URL for stocks
  websocket-url: "wss://stream.data.alpaca.markets/v2/iex"

# Service-specific configuration
app:
  # Symbols to subscribe to on startup
  stocks:
    - "AAPL"
    - "MSFT"
    - "AMZN"
