spring:
  profiles:
    include: common
  application:
    name: alert-processor-service
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/alert_db
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD}
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate # Automatically update the DB schema on startup
    show-sql: false # Log SQL statements for debugging
  # Flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  amqp:
    deserialization:
      trust:
        # Trust only our specific package for deserialization
        packages: "com.findataagg.common.messaging.model.*"

# Service-specific RabbitMQ configuration
app:
  rabbitmq:
    trades-queue-name: "stock.trade.queue"
    quotes-queue-name: "stock.quote.queue"
    trades-routing-key: "trade.stock.#"
    quotes-routing-key: "quote.stock.#"
    cache-invalidation-queue-name: "cache.invalidation.queue"
    cache-invalidation-routing-key: "cache.invalidation.#"
  # Partition management configuration
  partitioning:
    enabled: true
    retention-months: 24
    auto-cleanup: true
  # Alert configuration
  alerts:
    fallback-email: ${SYSTEM_ALERT_EMAIL:system-alerts@findataagg.com}