spring:
  profiles:
    include: common
  application:
    name: alert-processor-service
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/alert_db
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update # Automatically update the DB schema on startup
    show-sql: false # Log SQL statements for debugging

# Service-specific RabbitMQ configuration
app:
  rabbitmq:
    queue-name: "stock.price.queue"
    routing-key: "price.stock.#" # Listen to ALL stock prices