spring:
  profiles:
    include: common
  application:
    name: alert-processor-service
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/alert_db
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update # Automatically update the DB schema on startup
    show-sql: false # Log SQL statements for debugging
  amqp:
    deserialization:
      trust:
        # Trust only our specific package for deserialization
        packages: "com.findataagg.common.messaging.model.*"

# Service-specific RabbitMQ configuration
app:
  rabbitmq:
    trades-queue-name: "stock.trade.queue"
    quotes-queue-name: "stock.quote.queue"
    trades-routing-key: "trade.stock.#"
    quotes-routing-key: "quote.stock.#"